force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>TCK-{0000}</displayFormat>
        <label>Nome de Ticket</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Em Atendimento</fullName>
            </value>
            <value>
                <fullName>Escalado</fullName>
            </value>
            <value>
                <fullName>Resolvido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TicketController.cls
public with sharing class TicketController {
    
    // Essa tag @AuraEnabled é o que permite o nosso front-end (LWC) enxergar este método
    @AuraEnabled(cacheable=true)
    public static List<Ticket__c> getOpenTickets() {
        // Fazemos uma busca (SOQL) trazendo os tickets mais recentes que não estão resolvidos
        return [
            SELECT Id, Name, Status__c, Descricao__c 
            FROM Ticket__c 
            WHERE Status__c != 'Resolvido' 
            ORDER BY CreatedDate DESC 
            LIMIT 10
        ];
    }
}